# Generated by Django 5.2.8 on 2025-11-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('IdOffre', models.AutoField(primary_key=True, serialize=False)),
                ('OrganismeOffre', models.CharField(max_length=50)),
                ('NomContact', models.CharField(max_length=50)),
                ('PrenomContact', models.CharField(max_length=50)),
                ('MailContact', models.CharField(max_length=80)),
                ('IntituleOffre', models.CharField(max_length=50)),
                ('DateOffre', models.DateTimeField(auto_now_add=True)),
                ('DetailsOffre', models.CharField(max_length=10000)),
                ('EtatOffre', models.CharField(choices=[('attente', 'En attente de validation'), ('validee', 'Validée'), ('Refusee', 'Refusée'), ('Cloturée')], default='attente', max_length=20)),
                ('DureeOffre', models.CharField(max_length=10)),
                ('DateDebutOffre', models.DateField()),
                ('AdresseOffre', models.CharField(max_length=500)),
                ('VilleOffre', models.CharField(max_length=60)),
                ('CodePostalOffre', models.CharField(max_length=5)),
                ('RegionOffre', models.CharField(max_length=50)),
                ('DescriptionOrganisme', models.CharField(max_length=10000)),
            ],
        ),
    ]
