# Generated by Django 5.2.8 on 2025-11-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applistagecraft', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offre',
            old_name='DateDebutOffre',
            new_name='DateDebutStage',
        ),
    ]
