# Generated by Django 5.2.8 on 2025-11-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applistagecraft', '0002_rename_datedebutoffre_offre_datedebutstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('idRegion', models.AutoField(primary_key=True, serialize=False)),
                ('nomRegion', models.CharField(max_length=50)),
            ],
        ),
    ]
