# Generated by Django 5.2.8 on 2025-11-27 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applistagecraft', '0003_regions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regions',
            old_name='idRegion',
            new_name='IdRegion',
        ),
        migrations.RenameField(
            model_name='regions',
            old_name='nomRegion',
            new_name='NomRegion',
        ),
    ]
