# Generated by Django 5.2.8 on 2025-11-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applistagecraft', '0004_rename_idregion_regions_idregion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departements',
            fields=[
                ('IdDepartement', models.AutoField(primary_key=True, serialize=False)),
                ('NomDepartement', models.CharField(max_length=50)),
                ('CodeDepartement', models.CharField(max_length=5)),
            ],
        ),
    ]
