# Generated by Django 5.2.8 on 2025-11-28 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applistagecraft', '0005_departements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='RegionOffre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applistagecraft.regions'),
        ),
    ]
