# Generated by Django 5.2.8 on 2025-11-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applistagecraft', '0006_alter_offre_regionoffre'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='image',
            field=models.ImageField(default='imagesOffres/default.png', upload_to='imagesOffres'),
        ),
    ]
