# Generated by Django 5.2.8 on 2025-11-28 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applistagecraft', '0007_offre_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offre',
            old_name='image',
            new_name='ImageOffre',
        ),
    ]
