# Generated by Django 5.2.8 on 2025-11-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applistagecraft', '0008_rename_image_offre_imageoffre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='ImageOffre',
            field=models.ImageField(default='imagesEntreprises/deufault.png', upload_to='imagesEntreprises'),
        ),
    ]
