# Generated by Django 5.2.8 on 2025-11-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applistagecraft', '0009_alter_offre_imageoffre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='ImageOffre',
            field=models.ImageField(default='imagesEntreprises/logo.png', upload_to='imagesEntreprises'),
        ),
    ]
