# Generated by Django 5.2.8 on 2025-12-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applistagecraft', '0011_alter_offre_imageoffre'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatsOffres',
            fields=[
                ('IdEtatsOffres', models.AutoField(primary_key=True, serialize=False)),
                ('NomEtatsOffres', models.CharField(max_length=50)),
            ],
        ),
    ]
