# Generated by Django 5.2.8 on 2025-12-02 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applistagecraft', '0014_alter_offre_etatoffre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='EtatOffre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='applistagecraft.etatsoffres'),
        ),
    ]
