# Generated by Django 5.2.8 on 2025-12-08 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applistagecraft', '0015_alter_offre_etatoffre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('IdCandidature', models.AutoField(primary_key=True, serialize=False)),
                ('DateCandidature', models.DateTimeField(auto_now_add=True)),
                ('Etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applistagecraft.offre')),
            ],
        ),
    ]
